# Generated by Django 4.2.4 on 2023-08-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundData',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('regNo', models.IntegerField(primary_key=True, serialize=False)),
                ('netAsset', models.IntegerField()),
                ('cancelNav', models.FloatField()),
                ('annualEfficiency', models.FloatField()),
                ('investmentManager', models.CharField(max_length=200, null=True)),
                ('insInvNo', models.IntegerField(null=True)),
                ('retInvNo', models.IntegerField(null=True)),
            ],
        ),
    ]
