# Generated by Django 4.2.4 on 2023-08-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0002_funddata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundinfo',
            name='annualEfficiency',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='cancelNav',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fundinfo',
            name='netAsset',
            field=models.IntegerField(null=True),
        ),
    ]
