# Generated by Django 4.2.4 on 2023-08-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0003_alter_fundinfo_annualefficiency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddata',
            name='cancelNav',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='funddata',
            name='netAsset',
            field=models.IntegerField(null=True),
        ),
    ]
