# Generated by Django 4.2.4 on 2023-08-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0004_alter_funddata_cancelnav_alter_funddata_netasset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funddata',
            name='annualEfficiency',
            field=models.FloatField(null=True),
        ),
    ]
